name: Deploy Azure AD B2C Policies

on:
  push:
    branches:
      - master

env:
  B2C_SERVICE_PRINCIPAL_CLIENT_ID: "ee7e5f64-2e51-45a3-b4df-54892346c45f"
  
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace tokens in B2C policies
      uses: cschleiden/replace-tokens@v1.0
      with:
        tokenPrefix: "{Settings:"
        tokenSuffix: "}"
        files: "*.xml"
      env:
        Name: "adamtestadb2c.onmicrosoft.com"
        Production: "false"
        Tenant: "adamtestadb2c.onmicrosoft.com"
        PolicyPrefix: "B2C_1A_KCDemo_"
        DeploymentMode: "Development"
        DeveloperMode: "true"
        AppInsightsInstrumentationKey: "666351ec-57b2-410d-b1a9-de2dc94da60d"
        IdentityExperienceFrameworkAppId: "3e39f6e9-08c6-4864-9723-36e6c6d740ef"
        ProxyIdentityExperienceFrameworkAppId: "fac6e45c-c1db-4cd8-82fe-c8c8800c512e"
        FacebookClientId: "828534884165356"
        FacebookClientSecretKeyContainer: "B2C_1A_FacebookSecret"
        
    - name: Upload Base Policy
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "TrustFrameworkBase.xml"
        policy: B2C_1A_KCDemo_TrustFrameworkBase
        tenant: "adamtestadb2c.onmicrosoft.com"
        clientId: ${{ env.B2C_SERVICE_PRINCIPAL_CLIENT_ID }}
        clientSecret: ${{ secrets.B2C_SERVICE_PRINCIPAL_CLIENT_SECRET }}
    - name: Upload Extensions Policy
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "TrustFrameworkExtensions.xml"
        policy: B2C_1A_KCDemo_TrustFrameworkExtensions
        tenant: "adamtestadb2c.onmicrosoft.com"
        clientId: ${{ env.B2C_SERVICE_PRINCIPAL_CLIENT_ID }}
        clientSecret: ${{ secrets.B2C_SERVICE_PRINCIPAL_CLIENT_SECRET }}
    - name: Upload SignUpOrSignin Policy
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "SignUpOrSignin.xml"
        policy: B2C_1A_KCDemo_signup_signin
        tenant: "adamtestadb2c.onmicrosoft.com"
        clientId: ${{ env.B2C_SERVICE_PRINCIPAL_CLIENT_ID }}
        clientSecret: ${{ secrets.B2C_SERVICE_PRINCIPAL_CLIENT_SECRET }}